# Generated by Django 2.0.5 on 2018-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replys',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
